/*
* This Java source file was generated by the Gradle 'init' task.
*/
package sequality;

public class App {
	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) {
		Calculate calc = new Calculate();
		System.out.println(new App().getGreeting());
		System.out.println("Sum of 2 and 3 is "+calc.sum(2,3)+". Average is "+calc.sum_ave(2,3)+".");
		System.out.println("Sum of 1 to 10 is "+calc.total(1,10)+". Average is "+calc.total_ave(1,10)+".");
		System.out.println("Sum of odd of 1 to 10 is "+calc.total_odds(1,10)+". Sum of even is "+calc.total_even(1,10)+".");
	}
}
